 FEB 26 ASSIGNMENT

Q.1 Consider the below code to answer further questions.
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)
 Is there any difference in the data type of variables list_ and array_list ? 
If there is then write a code to print the data types of both the variables.

In [12]:
import numpy as np

In [4]:
list_=['1','2','3','4','5']

In [5]:
array_list=np.array(object=list_)

In [7]:
x=type(list_)

In [8]:
x

list

In [14]:
y=type(array_list)

In [15]:
y

numpy.ndarray

Q.2 Considering the following changes in the variable, array_list:
           array_list=np.array(object=list_, dtype=int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [16]:
array_list=np.array(object=list_, dtype=int)

In [17]:
array_list

array([1, 2, 3, 4, 5])

In [ ]:
data type of list=type(list_)
data type of arra_list=type(arra_list)


Q.3 Consider the below code to answer further questions.
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)

In [19]:
import numpy as np


In [20]:
num_list=[[1,2,3],[4,5,6]]

In [22]:
num_array=np.array(object=num_list)

In [23]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q.4 Write a code to find the following characteristics of variablr,num_array:

answer---
shape:
    l=[1,2,3,4,5]
    num_array=np.array(l)
    num_shape=num_array.shape
    
size:
    num_size=num_array.size

Q.5 Write a code to creat numpy array of 3*3 matrix containng zeros only, using a numpy array creation function

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q.6 Creat a identity matrix of shape (5,5) using numpy function?

In [27]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])